resourcePaths({
    images: [
        "src/images/img_scanlines.png",

        "src/images/img_butterfly1.png",
        "src/images/img_butterfly2.png",
        "src/images/img_crossblock.png",
        "src/images/img_flowerpot.png",
        "src/images/img_house1.png",
        "src/images/img_house2.png",
        "src/images/img_house3.png",
        "src/images/img_human_bald_gray.png",
        "src/images/img_human_bald.png",
        "src/images/img_human_bald2.png",
        "src/images/img_human_bald3.png",
        "src/images/img_human_beard.png",
        "src/images/img_lady1.png",
        "src/images/img_woman1.png",
        "src/images/img_woman2.png",
        "src/images/img_woman3.png",
        "src/images/img_human_sunglasses.png",
        "src/images/img_man1.png",
        "src/images/img_man2.png",
        "src/images/img_man3.png",
        "src/images/img_man_power.png",
        "src/images/img_man_power1.png",
        "src/images/img_man_power2.png",
        "src/images/img_man_power3.png",
        "src/images/img_pig1.png",
        "src/images/img_pig2.png",
        "src/images/img_pig3.png",
        "src/images/img_sheep1.png",
        "src/images/img_sheep2.png",
        "src/images/img_sheep3.png",
        "src/images/img_tree1.png",
        "src/images/img_tree2.png",
        "src/images/img_tree3.png",
        "src/images/tile_flower1.png",
        "src/images/tile_flower2.png",
        "src/images/tile_flower3.png",
        "src/images/tile_grass.png",
        "src/images/tile_grind1.png",
        "src/images/tile_stone.png",
        "src/images/tile_water.png",

        "src/images/img_block.png",
        "src/images/img_wall_stone.png",
        "src/images/img_wall_ice.png",
        "src/images/tile_snow.png",
        "src/images/tile_ice.png",
        "src/images/tile_sand.png",
        "src/images/img_cactus1.png",
        "src/images/img_cactus2.png",
        "src/images/tile_dirt.png",

        "src/images/tile_flower1.png",
        "src/images/tile_flower2.png",
        "src/images/tile_flower3.png",
        "src/images/tile_floor.png",
        "src/images/img_fence1.png",
        "src/images/img_fence2.png",
        "src/images/img_flowerpot.png",
        "src/images/img_rock.png",

        "src/images/img_surprise.png",
        "src/images/img_lever_red1.png",
        "src/images/img_lever_red2.png",
        "src/images/img_lever_green1.png",
        "src/images/img_lever_green2.png",
        "src/images/img_blackwall.png",
        "src/images/img_blackwall2.png",
        "src/images/tile_black.png",

        "src/images/img_screen.png",
        "src/images/img_stones.png",
        "src/images/tile_white.png",
    ],

    sounds: [
        "src/audio/snd_error.mp3",
        "src/audio/snd_doorlock.mp3",
        "src/audio/snd_tick.mp3",
        "src/audio/snd_bonus.mp3",
        "src/audio/snd_lever.mp3",
        "src/audio/snd_computer.mp3",
        "src/audio/snd_pig.mp3"
    ],

    music: [
        "src/audio/mus_grass.mp3",
        "src/audio/mus_snow.mp3",
        "src/audio/mus_desert.mp3",
        "src/audio/mus_cave.mp3",
        "src/audio/mus_credits.mp3"
    ]
});
